name: publish-build-engine
on:
  push:
    branches:
      - v*
jobs:
  publish-build-engine:
    name: publish-build-engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
        working-directory: ./scripts/build-engine
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          package: ./scripts/build-engine/package.json
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
